theme: jekyll-theme-minimal
title: "Daniel C. Ilut"
description: "Genomics, systematics, bioinformatics, plant breeding, philosophy, history, linguistics, and anyting else I find interesting"
show_downloads: "false"