theme: jekyll-theme-midnight
title: "Daniel C. Ilut"
description: "Genomics, systematics, plant breeding, bioinformatics, philosophy, history, linguistics, and anything else that comes along."
show_downloads: "false"
